# Modul #2 Tapşırıqları

In [1]:
# Lazım olan kitabxanalar
import numpy as np
import warnings

In [2]:
warnings.filterwarnings(action = 'ignore')
np.random.seed(seed = 42)

***
### Tapşırıq #1
- Tək dəyərlərdən ibarət (1 dən 100-ə kimi) array data strukturu yarat

In [29]:
array = np.arange(start=1, stop=100, step=2)
array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

- Yaradılan həmin array data strukturunu 5 sətir və 10 sütun halına sal

In [30]:
array = np.reshape(array, newshape=(5,10))
#array = array.reshape((5, 10))
array

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

- Array data strukturunda olan dəyərlərin sırasını random şəkildə qarışdır

In [31]:
# kodu bu şərhin altına yaz
np.random.shuffle(array)

array

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

- Array data strukturunda olan dəyərlərin sırasını əvvəlki ardıcıllığa uygun olaraq dəyişdir

In [32]:
array = np.sort(array, axis=0)
array 

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

- Array data strukturunu düzləşdir yəni ilk yaradıldığı hala qaytar

In [34]:
array = array.flatten()
array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

- Array data strukturunda olan dəyərlərdən 50-dən böyük olan dəyərləri filterlə 

In [35]:
array = array[array > 50]
array

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

***
### Tapşırıq #2
- Bütün dəyərləri 0-dan ibarət olan int64 data növlü 3 sətir və 4 sütundan ibarət array yarat 

In [39]:
zeros = np.zeros(shape = (3, 4), dtype = 'int64')
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

- Bütün dəyərləri 1-dan ibarət olan int64 data növlü 3 sətir və 4 sütundan ibarət array yarat 

In [40]:
ones = np.ones(shape = (3, 4), dtype = 'int64')
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

- Hər iki array-i vertikal şəkildə birləşdir (birləşdirmə zamanı array sırasının fərqi yoxdur)

In [57]:
combined_array = np.vstack(tup=(zeros, ones))
#combined_array = np.concatenate([zeros, ones])
combined_array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

- Birləşdirilən array data strukturunda olan sətirlərin sayı qədər dəyərdən ibarət olan ardıcıl şəkildə düzülmüş array yarat (0-dan başlayır ilk dəyər)

In [58]:
new_array = np.arange(combined_array.shape[0] * combined_array.shape[1])
new_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

- Yeni yaradılan arrayin ölçüsünü dəyişərək dəyərlərin sayı qədər sətir yarat, yəni hər bir dəyər bir sətir olsun

In [59]:
new_array = new_array.reshape((combined_array.shape[0] * combined_array.shape[1], 1))
new_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

- Bu arrayi **combined_array**-ə horizontal şəkildə birləşdir

In [65]:
array = np.hstack(tup=(combined_array.reshape(1, -1), new_array.reshape(1, -1)))
# array = np.concatenate([combined_array.reshape(1, -1), new_array.reshape(1, -1)], axis=1)
array

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  2,  3,  4,  5,  6,  7,
         8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

- Horizontal şəkildə birləşdirilmiş array-dən unikal dəyərlərdən ibarət yeni array yarat

In [68]:
unique_array = np.unique(ar=array)
unique_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

- Unikal dəyərlərdən ibarət olan array-də 2-ə bərabər və ya böyük dəyərləri "2-ə bərabər və ya böyük" 2-dən kiçik dəyərləri isə "2-dən kiçik" kimi əvəzlə

In [70]:
array = np.where(unique_array >= 2, "2-ə bərabər və ya böyük", "2-dən kiçik")
array

array(['2-dən kiçik', '2-dən kiçik', '2-ə bərabər və ya böyük',
       '2-ə bərabər və ya böyük', '2-ə bərabər və ya böyük',
       '2-ə bərabər və ya böyük', '2-ə bərabər və ya böyük',
       '2-ə bərabər və ya böyük', '2-ə bərabər və ya böyük',
       '2-ə bərabər və ya böyük', '2-ə bərabər və ya böyük',
       '2-ə bərabər və ya böyük', '2-ə bərabər və ya böyük',
       '2-ə bərabər və ya böyük', '2-ə bərabər və ya böyük',
       '2-ə bərabər və ya böyük', '2-ə bərabər və ya böyük',
       '2-ə bərabər və ya böyük', '2-ə bərabər və ya böyük',
       '2-ə bərabər və ya böyük', '2-ə bərabər və ya böyük',
       '2-ə bərabər və ya böyük', '2-ə bərabər və ya böyük',
       '2-ə bərabər və ya böyük'], dtype='<U23')

***
### Tapşırıq #3
- Dəyərləri 1-dən 24-ə kimi (24 daxildir) 4 sətir və 6 sütundan ibarət array yarat

In [72]:
array = np.arange(1, 25).reshape((4, 6))
array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

- Array-də ilk sətirin sonuncu dəyərini və son sətrin ilk dəyərini filterlə

In [74]:
print(f"Ilk sətirin sonuncu dəyəri: {array[0][-1]}")
print(f"Son sətrin ilk dəyəri: {array[-1][0]}")

Ilk sətirin sonuncu dəyəri: 6
Son sətrin ilk dəyəri: 19


- Array-də ilk sətirin və 3-cü sətirlərin son 3 dəyərini filterlə

In [75]:
print(f"Ilk sətirin son 3 dəyəri: {array[0][-3:]}")
print(f"Üçüncü sətrin son 3  dəyəri: {array[2][-3:]}")

Ilk sətirin son 3 dəyəri: [4 5 6]
Üçüncü sətrin son 3  dəyəri: [16 17 18]


- Array-də bütün sətirlərin və 3-cü və 4-cü dəyərlərini filterlə

In [79]:
print(f"Array-də bütün sətirlərin və 3-cü və 4-cü dəyərləri: {array[:, [3, 4]]}")

Array-də bütün sətirlərin və 3-cü və 4-cü dəyərləri: [[ 4  5]
 [10 11]
 [16 17]
 [22 23]]


- Array-də maksimum dəyəri göstər

In [82]:
print(f"Array-də maksimum dəyəri: {array.max()}")

Array-də maksimum dəyəri: 24


- Array-də minimum dəyəri göstər

In [83]:
print(f"Array-də maksimum dəyəri: {array.min()}")

Array-də maksimum dəyəri: 1


- Array-də ortalama dəyəri göstər

In [84]:
print(f"Array-də ortalama dəyəri göstər: {array.mean()}")

Array-də ortalama dəyəri göstər: 12.5


- Array-də median dəyəri göstər

In [87]:
print(f"Array-də median dəyəri göstər: {np.median(array)}")

Array-də median dəyəri göstər: 12.5


- Təsadüfi 10 integer dəyərdən ibarət, minimum ala biləcəyi dəyər 10 maksimum ala biləcəyi dəyər isə 100 ola biləcək array yarat

In [88]:
np.random.seed(seed = 42)

random_array = np.random.randint(low = 10, high = 100, size=10)
random_array

array([61, 24, 81, 70, 30, 92, 96, 84, 84, 97])

- Bu array-də maksimum dəyərin indeksini göstər

In [92]:
print(f"Array-də maksimum dəyərin indeksi: {random_array.argmax()}")
print(f"Array-də maksimum dəyər: {random_array.max()}")
print(f"Array-də maksimum dəyər: {random_array[random_array.argmax()]}")

Array-də maksimum dəyərin indeksi: 9
Array-də maksimum dəyər: 97
Array-də maksimum dəyər: 97


- Bu array-də minimum dəyərin indeksini göstər

In [93]:
print(f"Array-də maksimum dəyərin indeksi: {random_array.argmin()}")
print(f"Array-də maksimum dəyər: {random_array.min()}")
print(f"Array-də maksimum dəyər: {random_array[random_array.argmin()]}")

Array-də maksimum dəyərin indeksi: 1
Array-də maksimum dəyər: 24
Array-də maksimum dəyər: 24


***
### Tapşırıq #4
- Dəyərləri Əsəd, Gülnar, Anar və Rəna-dan ibarət olan array yarat

In [104]:
array = np.array(['Əsəd', 'Gülnar', 'Anar', 'Rəna'])
array

array(['Əsəd', 'Gülnar', 'Anar', 'Rəna'], dtype='<U6')

- Array-də olan bütün adların ilk hərfini kiçilt

In [105]:
array = np.array([i[0].lower() + i[1:] for i in array])
array

array(['əsəd', 'gülnar', 'anar', 'rəna'], dtype='<U6')

- Array-də olan bütün adların bütün hərflərini böyüt

In [109]:
array = np.char.upper(array)
array

array(['ƏSƏD', 'GÜLNAR', 'ANAR', 'RƏNA'], dtype='<U6')

- Array-də olan bütün adların ilk hərfini böyük saxla qalan hərfləri kiçilt

In [110]:
array = np.char.capitalize(array)
array

array(['Əsəd', 'Gülnar', 'Anar', 'Rəna'], dtype='<U6')

- Array-də A hərfi ilə başlayan adı filterlə

In [114]:
array[np.char.startswith(array, "A")]

array(['Anar'], dtype='<U6')

- Array-də r hərfi ilə bitən ad(ları) filterlə

In [115]:
array[np.char.endswith(array, "r")]

array(['Gülnar', 'Anar'], dtype='<U6')